class TranslationTargets:
    PRODUCT_NAME = 'PRODUCT_NAME'
    PRODUCT_DESCRIPTION = 'PRODUCT_DESCRIPTION'
    CATEGORY_NAME = 'CATEGORY_NAME'
    CHARACTERISTIC_NAME = 'CHARACTERISTIC_NAME'
    CHARACTERISTIC_VALUE = 'CHARACTERISTIC_VALUE'
